openapi: "3.1.0"
info:
  title: "AMRO Recipe Finder API"
  description: "Home Assignment for ABN AMRO"
  version: "1.0.0"
servers:
  - url: "https://localhost:9000"
    description: "Localhost server"
paths:
  /api/v1/auth/register:
    post:
      summary: "POST api/v1/auth/register"
      operationId: "register"
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/RegisterRequest"
        required: true
      responses:
        "200":
          description: "OK"
          content:
            '*/*':
              schema:
                $ref: "#/components/schemas/AuthenticationResponse"
        "400":
            description: "Bad Request"
            content:
                '*/*':
                schema:
                    $ref: "#/components/schemas/AuthenticationResponse"
  /api/v1/auth/login:
    post:
      summary: "POST api/v1/auth/login"
      operationId: "login"
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/AuthenticationRequest"
        required: true
      responses:
        "200":
          description: "OK"
          content:
            '*/*':
              schema:
                $ref: "#/components/schemas/AuthenticationResponse"
        "400":
          description: "Bad Request"
          content:
            '*/*':
              schema:
                $ref: "#/components/schemas/AuthenticationResponse"
        "401":
          description: "Unauthorized"
          content:
            '*/*':
              schema:
                $ref: "#/components/schemas/AuthenticationResponse"
components:
  schemas:
    RegisterRequest:
      type: "object"
      properties:
        firstName:
          type: "string"
          description: "a-z, A-Z, hyphen, space"
        lastName:
          type: "string"
          description: "a-z, A-Z, hyphen, space"
        email:
          type: "string"
          description: "valid email address"
        password:
          type: "string"
    AuthenticationResponse:
      type: "object"
      properties:
        statusCode:
          type: "integer"
          format: "int32"
        message:
          type: "string"
        token:
          type: "string"
    AuthenticationRequest:
      type: "object"
      properties:
        email:
          type: "string"
        password:
          type: "string"
