openapi: "3.1.0"
info:
  title: "AMRO Recipe Finder API"
  description: "Home Assignment for ABN AMRO"
  version: "1.0.0"
servers:
  - url: "https://localhost:9000"
paths:
  /api/v1/recipes/{recipeId}:
    get:
      summary: "GET api/v1/recipes/{recipeId}"
      operationId: "getRecipe"
      parameters:
        - name: "recipeId"
          in: "path"
          required: true
          schema:
            type: "integer"
            format: "integer"
        - name: "Authorization"
          in: "header"
          required: true
          schema:
            type: "string"
            format: "Bearer <token>"
      responses:
        "200":
          description: "OK"
          content:
            '*/*':
              schema:
                $ref: "#/components/schemas/RecipeResponse"
        "404":
          description: "Not Found"
          content:
            '*/*':
              schema:
                $ref: "#/components/schemas/ErrorRecipeResponse"
        "403":
          description: "Forbidden"
          content:
            '*/*':
              schema:
                $ref: "#/components/schemas/ErrorRecipeResponse"
    put:
      summary: "PUT api/v1/recipes/{recipeId}"
      operationId: "updateRecipe"
      parameters:
        - name: "recipeId"
          in: "path"
          required: true
          schema:
            type: "integer"
            format: "integer"
        - name: "Authorization"
          in: "header"
          required: true
          schema:
            type: "string"
            format: "Bearer <token>"
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/Recipe"
        required: true
      responses:
        "201":
          description: "Created"
          content:
            '*/*':
              schema:
                $ref: "#/components/schemas/RecipeResponse"
        "404":
          description: "Not Found"
          content:
            '*/*':
              schema:
                $ref: "#/components/schemas/ErrorUpdateResponse"
        "403":
          description: "Forbidden"
          content:
            '*/*':
              schema:
                $ref: "#/components/schemas/ErrorUpdateResponse"
        "400":
          description: "Bad Request"
          content:
            '*/*':
              schema:
                $ref: "#/components/schemas/ErrorUpdateResponse"

    delete:
      summary: "DELETE api/v1/recipes/{recipeId}"
      operationId: "deleteRecipe"
      parameters:
        - name: "recipeId"
          in: "path"
          required: true
          schema:
            type: "integer"
            format: "integer"
        - name: "Authorization"
          in: "header"
          required: true
          schema:
            type: "string"
            format: "Bearer <token>"
      responses:
        "200":
          description: "OK"
          content:
            '*/*':
              schema:
                $ref: "#/components/schemas/RecipeDeleteResponse"
        "403":
          description: "Forbidden"
        "404":
          description: "Not Found"
          content:
            "*/*":
              schema:
                $ref: "#/components/schemas/RecipeNotFoundResponse"
  /api/v1/recipes:
    get:
      summary: "GET api/v1/recipes"
      operationId: "getRecipes"
      parameters:
        - name: "Authorization"
          in: "header"
          required: true
          schema:
            type: "string"
            format: "Bearer <token>"
        - name: "description"
          in: "query"
          required: false
          schema:
            type: "string"
        - name: "isVegan"
          in: "query"
          required: false
          schema:
            type: "boolean"
        - name: "numServings"
          in: "query"
          required: false
          schema:
            type: "integer"
            format: "integer"
        - name: "ingredients"
          in: "query"
          required: false
          schema:
            type: "string"
        - name: "excludeIngredients"
          in: "query"
          required: false
          schema:
            type: "string"
        - name: "page"
          in: "query"
          required: false
          schema:
            type: "integer"
            format: "integer"
            default: "0"
        - name: "pageSize"
          in: "query"
          required: false
          schema:
            type: "integer"
            format: "integer"
            default: "100"
      responses:
        "200":
          description: "OK"
          content:
            '*/*':
              schema:
                $ref: "#/components/schemas/PageableRecipes"
        "403":
          description: "Forbidden"
    post:
      summary: "POST api/v1/recipes"
      operationId: "createRecipe"
      parameters:
        - name: "Authorization"
          in: "header"
          required: true
          schema:
            type: "string"
            format: "Bearer <token>"
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/Recipe"
        required: true
      responses:
        "201":
          description: "Created"
          content:
            '*/*':
              schema:
                $ref: "#/components/schemas/RecipeResponse"
        "403":
          description: "Forbidden"
        "400":
          description: "Bad Request"
          content:
            '*/*':
              schema:
                $ref: "#/components/schemas/ErrorUpdateResponse"
components:
  schemas:
    RecipeDTO:
      type: "object"
      properties:
        id:
          type: "integer"
          format: "integer"
        description:
          type: "string"
        is_vegan:
          type: "boolean"
        num_servings:
          type: "integer"
          format: "integer"
        ingredients:
          type: "array"
          items:
            type: "string"
    RecipeResponse:
      type: "object"
      properties:
        StatusCode:
          type: "integer"
          format: "integer"
        message:
          type: "string"
        payload:
          $ref: "#/components/schemas/RecipeDTO"
    RecipeDeleteResponse:
      type: "object"
      properties:
        statusCode:
          type: integer
        message:
          type: integer
        payload:
          type: string
    RecipeNotFoundResponse:
      type: "object"
      properties:
        message:
          type: string
        status:
          type: integer
        timestamp:
          type: string
    ErrorRecipeResponse:
      type: "object"
      properties:
        message:
          type: string
        status:
          type: string
        timestamp:
          type: string
    ErrorUpdateResponse:
      type: "object"
      properties:
        statusCode:
          type: integer
        message:
          type: string
    PaginatedRecipeResponse:
      type: "object"
      properties:
        recipes:
          $ref: "#/components/schemas/RecipeDTO"
    Recipe:
      type: "object"
      properties:
        id:
          type: "integer"
          format: "integer"
        description:
          type: "string"
        is_vegan:
          type: "boolean"
        num_servings:
          type: "integer"
          format: "integer"
        ingredients:
          type: "array"
          items:
            type: "string"
    PageableRecipe:
      type: object
      properties:
        id:
          type: integer
        description:
          type: string
        ingredients:
          type: array
          items:
            type: string
        is_vegan:
          type: boolean
        num_servings:
          type: integer
    PageableSort:
      type: object
      properties:
        empty:
          type: boolean
        unsorted:
          type: boolean
        sorted:
          type: boolean
    Pageable:
      type: object
      properties:
        pageNumber:
          type: integer
        pageSize:
          type: integer
        sort:
          $ref: '#/components/schemas/PageableSort'
        offset:
          type: integer
        unpaged:
          type: boolean
        paged:
          type: boolean
    PageableRecipes:
      type: object
      properties:
        totalElements:
          type: integer
        totalPages:
          type: integer
        first:
          type: boolean
        last:
          type: boolean
        size:
          type: integer
        content:
          type: array
          items:
            $ref: '#/components/schemas/PageableRecipe'
        number:
          type: integer
        sort:
          $ref: '#/components/schemas/PageableSort'
        numberOfElements:
          type: integer
        pageable:
          $ref: '#/components/schemas/Pageable'
        empty:
          type: boolean
